import { 
  angular, aws, azure, csharp, cpp, css, dart, docker,
  express, figma, firebase, flutter, git, go, html,
  java, js, kotlin, kubernetes, linux, mongo, next,
  node, php, psql, python, react, rust, solidity,
  svelte, tailwind, ts, vue 
} from '../assets';

export const TECH_STACK_CONFIG = [
  { name: "angular", icon: angular },
  { name: "aws", icon: aws },
  { name: "azure", icon: azure },
  { name: "c#", icon: csharp },
  { name: "c++", icon: cpp },
  { name: "css", icon: css },
  { name: "dart", icon: dart },
  { name: "docker", icon: docker },
  { name: "express", icon: express },
  { name: "figma", icon: figma },
  { name: "firebase", icon: firebase },
  { name: "flutter", icon: flutter },
  { name: "git", icon: git },
  { name: "golang", icon: go },
  { name: "html", icon: html },
  { name: "java", icon: java },
  { name: "javascript", icon: js },
  { name: "kotlin", icon: kotlin },
  { name: "kubernetes", icon: kubernetes },
  { name: "linux", icon: linux },
  { name: "mongodb", icon: mongo },
  { name: "next", icon: next },
  { name: "node", icon: node },
  { name: "php", icon: php },
  { name: "postgresql", icon: psql },
  { name: "python", icon: python },
  { name: "react", icon: react },
  { name: "rust", icon: rust },
  { name: "solidity", icon: solidity },
  { name: "svelte", icon: svelte },
  { name: "tailwind", icon: tailwind },
  { name: "typescript", icon: ts },
  { name: "vue", icon: vue },
].sort((a, b) => a.name.localeCompare(b.name)); 